// HydroD V6.1-02 started 2023-02-27 09:44:57

Workspace.AccelerationUnit = "m/s^2";
Workspace.AngleUnit = "deg";
Workspace.AreaUnit = "m^2";
Workspace.DensityUnit = "kg/m^3";
Workspace.Description = null;
Workspace.ForceTimeDividedByLengthUnit = null;
Workspace.ForceTimeLengthUnit = null;
Workspace.ForceTimeSquaredDividedByLengthSquaredUnit = null;
Workspace.ForceTimeSquaredLengthUnit = null;
Workspace.ForceUnit = "N";
Workspace.FractionUnit = "%";
Workspace.FrequencyUnit = "rad/s";
Workspace.KinematicViscosityUnit = "m^2/s";
Workspace.LengthAngleUnit = "m*rad";
Workspace.LengthUnit = "m";
Workspace.LinearMomentumUnit = null;
Workspace.MassLengthUnit = "kg*m";
Workspace.MassMomentOfInertiaUnit = "kg*m^2";
Workspace.MassUnit = "kg";
Workspace.MomentAngleUnit = "N*m*rad";
Workspace.MomentUnit = "N*m";
Workspace.NumberOfDigits = 5;
Workspace.PressureUnit = "Pa";
Workspace.ShowScientificNotationGreaterThanOrEqualTo = 100000;
Workspace.ShowScientificNotationLessThan = 0.1;
Workspace.StiffnessUnit = null;
Workspace.TimeUnit = "s";
Workspace.VelocityUnit = "m/s";
Workspace.VolumeUnit = "m^3";
Workspace.WaveSpectralDensityUnit = "m^2*s";
//
Workspace = Reference("/Workspace");
Environment = new EnvironmentFolder(Workspace, "Environment");
Environment.Description = null;
//
Workspace = Reference("/Workspace");
Properties = new CompartmentPropertiesFolder(Workspace, "Properties");
Properties.Description = null;
//
Workspace = Reference("/Workspace");
StabilityProperties = new StabilityPropertiesFolder(Workspace, "StabilityProperties");
StabilityProperties.Description = null;
//
Workspace = Reference("/Workspace");
Models = new ModelsFolder(Workspace, "Models");
Models.Description = null;
//
Workspace = Reference("/Workspace");
HydroModels = new HydroModelsFolder(Workspace, "HydroModels");
HydroModels.Description = null;
//
Workspace = Reference("/Workspace");
Rules = new RulesFolder(Workspace, "Rules");
Rules.Description = null;
//
Workspace = Reference("/Workspace");
Analyses = new AnalysesFolder(Workspace, "Analyses");
Analyses.Description = null;
//
Workspace = Reference("/Workspace");
Plots = new PlotsFolder(Workspace, "Plots");
Plots.Description = null;
//
Workspace = Reference("/Workspace");
Tables = new TablesFolder(Workspace, "Tables");
Tables.Description = null;
//
Workspace = Reference("/Workspace");
Pictures = new PicturesFolder(Workspace, "Pictures");
Pictures.Description = null;
//
Workspace = Reference("/Workspace");
Reports = new ReportsFolder(Workspace, "Reports");
Reports.Description = null;
//
Workspace = Reference("/Workspace");
ViewSettings = new ViewSettingsFolder(Workspace, "ViewSettings");
ViewSettings.Description = null;
//
ViewSettings = Reference("/Workspace/ViewSettings");
ViewSetting1 = new ViewSetting(ViewSettings, "ViewSetting1");
ViewSetting1.BackgroundBottomColor = Color.FromArgb(255, 0, 0, 0);
ViewSetting1.BackgroundColor = Color.FromArgb(255, 0, 0, 0);
ViewSetting1.BackgroundGradient = false;
ViewSetting1.BackgroundTopColor = Color.FromArgb(255, 169, 169, 169);
ViewSetting1.BillboardLabelDepthOffset = 0 m;
ViewSetting1.BillboardLabelHeight = 10;
ViewSetting1.CameraPosition = new Position3D(240 m, -120 m, 80 m);
ViewSetting1.CameraType = CameraType.Perspective;
ViewSetting1.CoordinateSystemLabelBackground = Color.FromArgb(0, 0, 0, 1);
ViewSetting1.CoordinateSystemLabelColor = Color.FromArgb(0, 0, 0, 1);
ViewSetting1.Description = null;
ViewSetting1.FarPlaneDistance = 1000000 m;
ViewSetting1.FieldOfView = 45 deg;
ViewSetting1.GridColor = Color.FromArgb(0, 0, 0, 1);
ViewSetting1.GridLength = 100 m;
ViewSetting1.GridMajorInterval = 10 m;
ViewSetting1.GridMinorInterval = 1 m;
ViewSetting1.GridThickness = 0.04 m;
ViewSetting1.GridWidth = 100 m;
ViewSetting1.InputCoordinateSystemDiameter = 0.5 m;
ViewSetting1.InputCoordinateSystemLabel = "Input system";
ViewSetting1.InputCoordinateSystemSize = 3 m;
ViewSetting1.LabelBackground = null;
ViewSetting1.LabelBorderColor = null;
ViewSetting1.LabelColor = Color.FromArgb(255, 0, 0, 0);
ViewSetting1.LabelPinColor = null;
ViewSetting1.LineThicknessScale = 0.1 m;
ViewSetting1.LookDirection = new Direction3D(-240 m, 120 m, -80 m);
ViewSetting1.MaxNumberOfLabels = 10000;
ViewSetting1.NearPlaneDistance = 0.1 m;
ViewSetting1.OpenWhenLoaded = true;
ViewSetting1.OrthographicWidth = 100 m;
ViewSetting1.ShowCoordinateSystem = true;
ViewSetting1.ShowGrid = false;
ViewSetting1.ShowInputCoordinateSystem = false;
ViewSetting1.SpatialLabelHeight = 1 m;
ViewSetting1.UpDirection = new Vector3D(0, 0, 1);
ViewSetting1.ViewSubtitle = null;
ViewSetting1.ViewTitle = null;
ViewSetting1.ViewTitleColor = Color.FromArgb(0, 0, 0, 1);
//
ViewSetting1 = Reference("/Workspace/ViewSettings/ViewSetting1");
HydroViewSetting1 = new HydroViewSetting(ViewSetting1, "HydroViewSetting1");
HydroViewSetting1.BaseLineColor = Color.FromArgb(0, 0, 0, 1);
HydroViewSetting1.BeamColor = Color.FromArgb(255, 128, 128, 128);
HydroViewSetting1.BeamDivisions = 18;
HydroViewSetting1.BeamThickness = 1;
HydroViewSetting1.BuoyancyModelColor = Color.FromArgb(255, 247, 150, 70);
HydroViewSetting1.CompartmentDamageColor = Color.FromArgb(255, 255, 99, 71);
HydroViewSetting1.CompartmentDeckTankColor = Color.FromArgb(255, 255, 99, 71);
HydroViewSetting1.CompartmentEdgeColor = Color.FromArgb(0, 0, 0, 1);
HydroViewSetting1.CompartmentEdgeThickness = 2;
HydroViewSetting1.CompartmentFloodedByOpeningColor = Color.FromArgb(255, 255, 99, 71);
HydroViewSetting1.CompartmentPlateBackColor = Color.FromArgb(255, 0, 255, 127);
HydroViewSetting1.CompartmentPlateColor = Color.FromArgb(255, 216, 191, 216);
HydroViewSetting1.CompartmentSharpEdgeLimit = 45 deg;
HydroViewSetting1.DeckEdgePointSize = 1 m;
HydroViewSetting1.Description = null;
HydroViewSetting1.GlobalCoordinateSystemDiameter = 0.5 m;
HydroViewSetting1.GlobalCoordinateSystemSize = 3 m;
HydroViewSetting1.HydroPressureLoadArrowColor = Color.FromArgb(255, 173, 216, 230);
HydroViewSetting1.HydroPressureLoadArrowDiameter = 0.5 m;
HydroViewSetting1.HydroPressureLoadArrowDivisions = 4;
HydroViewSetting1.HydroPressureLoadArrowLength = 3 m;
HydroViewSetting1.KeelLineColor = Color.FromArgb(0, 0, 0, 1);
HydroViewSetting1.KeelLineDiameter = 0.1 m;
HydroViewSetting1.LoadCrossSectionArrowDiameter = 2 m;
HydroViewSetting1.LoadCrossSectionArrowLength = 10 m;
HydroViewSetting1.LoadCrossSectionFrameColor = Color.FromArgb(255, 0, 0, 0);
HydroViewSetting1.LoadCrossSectionFrameThickness = 1;
HydroViewSetting1.LoadCrossSectionPointSize = 3 m;
HydroViewSetting1.MarkerColor = Color.FromArgb(255, 255, 99, 71);
HydroViewSetting1.MarkerDiameter = 3 m;
HydroViewSetting1.OpeningDiameter = 3 m;
HydroViewSetting1.PanelEdgeColor = Color.FromArgb(255, 0, 0, 0);
HydroViewSetting1.PanelEdgeThickness = 1;
HydroViewSetting1.PanelShrinkFactor = new Fraction(0.1);
HydroViewSetting1.PerpendicularHeight = 30 m;
HydroViewSetting1.PlateBackColor = Color.FromArgb(255, 255, 165, 0);
HydroViewSetting1.PlateColor = Color.FromArgb(255, 178, 34, 34);
HydroViewSetting1.PointMassColor = Color.FromArgb(255, 147, 137, 83);
HydroViewSetting1.PointMassDiameter = 5 m;
HydroViewSetting1.PointMassDivisions = 16;
HydroViewSetting1.SolidBackColor = Color.FromArgb(255, 0, 0, 255);
HydroViewSetting1.SolidColor = Color.FromArgb(255, 0, 128, 0);
HydroViewSetting1.SpecifyCompartmentPlateBackColor = false;
HydroViewSetting1.SpecifyPlateBackColor = true;
HydroViewSetting1.SpecifySolidBackColor = true;
HydroViewSetting1.ThrusterForceColor = Color.FromArgb(255, 255, 165, 0);
HydroViewSetting1.ThrusterForceRadius = 3 m;
HydroViewSetting1.UnprotectedOpeningColor = Color.FromArgb(255, 255, 165, 0);
HydroViewSetting1.WatertightOpeningColor = Color.FromArgb(255, 0, 128, 0);
HydroViewSetting1.WeathertightOpeningColor = Color.FromArgb(255, 255, 0, 0);
//
Workspace = Reference("/Workspace");
Wizards = new WizardsFolder(Workspace, "Wizards");
Wizards.Description = null;


Directions1 = new Directions(Environment, "Directions1");
DirectionSet1 = new DirectionSet(Directions1, "DirectionSet1");
DirectionSet1.Items[0].From = 0 deg;
DirectionSet1.Items[0].To = 180 deg;
DirectionSet1.Items[0].Step = 45 deg;

Water1 = new Water(Environment, "Water1");

FrequencySet1 = new FrequencySet(Water1, "FrequencySet1");
FrequencySet1.WavePeriodItems.Add(new TimeInterval());
FrequencySet1.WavePeriodItems[0].From = 4 s;
FrequencySet1.WavePeriodItems[0].To = 10 s;
FrequencySet1.WavePeriodItems[0].Step = 2 s;

FrequencySet1.WavePeriodItems.Add(new TimeInterval());
FrequencySet1.WavePeriodItems[1].From = 10 s;
FrequencySet1.WavePeriodItems[1].To = 30 s;
FrequencySet1.WavePeriodItems[1].Step = 1 s;

FrequencySet1.WavePeriodItems.Add(new TimeInterval());
FrequencySet1.WavePeriodItems[2].From = 30 s;
FrequencySet1.WavePeriodItems[2].To = 50 s;
FrequencySet1.WavePeriodItems[2].Step = 2 s;

FrequencySet1.WavePeriodItems.Add(new TimeInterval());
FrequencySet1.WavePeriodItems[3].From = 50 s;
FrequencySet1.WavePeriodItems[3].To = 120 s;
FrequencySet1.WavePeriodItems[3].Step = 5 s;

Location1 = new Location(Environment, "Location1");
Location1.Gravity = 9.80665 m/s^2;
Location1.WaterDepth = 300 m;

FrequencyDomainCondition1 = new FrequencyDomainCondition(Location1, "FrequencyDomainCondition1");
FrequencyDomainCondition1.DirectionSet = DirectionSet1;
FrequencyDomainCondition1.FrequencySet = FrequencySet1;

HydroModel1 = new HydroModel(HydroModels, "HydroModel1");
HydroModel1.FPx = 1 m;

Panel = new ElementModel(Models, "Panel");
Panel.FileName = "S:\\Master\\Analysis\\Convergence study\\Linear_analysis\\Mesh_1m\\Mesh_1m\\GeniEActivity1\\T1.FEM";

Morison = new ElementModel(Models, "Morison");
Morison.FileName = "S:\\Master\\Analysis\\Convergence study\\Linear_analysis\\Mesh_1m\\Mesh_1m\\GeniEActivity1\\T6.FEM";

Compartment = new ElementModel(Models, "Compartment");
Compartment.FileName = "C:\\Users\\stian\\OneDrive - NTNU\\5. klasse\\Masteroppgave\\VolturnUS-S\\Final_js\\T5.FEM";

Free_surface = new ElementModel(Models, "Free_surface");
Free_surface.FileName = "C:\\Users\\stian\\OneDrive - NTNU\\5. klasse\\Masteroppgave\\VolturnUS-S\\Final_js\\T73.FEM";

Internal_lid = new ElementModel(Models, "Internal_lid");
Internal_lid.FileName = "C:\\Users\\stian\\OneDrive - NTNU\\5. klasse\\Masteroppgave\\VolturnUS-S\\Final_js\\T23.FEM";


PanelModel1 = new PanelModel(HydroModel1, "PanelModel1");
PanelModel1.ElementModel = Panel;
PanelModel1.SymmetryXZ = true;
PanelModel1.ShowHydroPressureArrows = true;


Morison2DProperties = new Morison2DProperties(Properties, "Morison2DProperties");

Col1 = new Morison2DProperty(Morison2DProperties, "Col1");
Col1.Cdy = 1;
Col1.Cdz = 1;
Col1.Cay = 1;
Col1.Caz = 1;

Col2 = new Morison2DProperty(Morison2DProperties, "Col2");
Col2.Cdy = 1;
Col2.Cdz = 1;
Col2.Cay = 1;
Col2.Caz = 1;

Pon = new Morison2DProperty(Morison2DProperties, "Pon");
Pon.Cdy = 1;
Pon.Cdz = 1;
Pon.Cay = 1;
Pon.Caz = 1;

AnchorProperties1 = new AnchorProperties(Properties, "AnchorProperties1");
AnchorProperty1 = new AnchorProperty(AnchorProperties1, "AnchorProperty1");
AnchorProperty1.HorizontalStiffness = 864.629 N/m;
AnchorProperty1.VerticalStiffness = 661.622 N/m;
AnchorProperty1.PreTension = 1088.73 N;
AnchorProperty1.AngleSeaSurface = 37.423 deg;


LoadingConditions1 = new LoadingConditions(HydroModel1, "LoadingConditions1");
LoadingCondition1.Location = Location1;
LoadingCondition1.WaterLineZ = 0 m;
LoadingCondition1.TrimAngle = 0 deg;


MorisonModel1 = new MorisonModel(HydroModel1, "MorisonModel1");
MorisonModel1.ElementModel = Morison;
MorisonModel1.UpdateSections();
MorisonModel1.Sections[0].Morison2DProperty = Col1;
MorisonModel1.Sections[1].Morison2DProperty = Pon;
MorisonModel1.Sections[2].Morison2DProperty = Col2;
MorisonModel1.Sections[0].DragOnly = true;
MorisonModel1.Sections[1].DragOnly = true;
MorisonModel1.Sections[2].DragOnly = true;

AnchorElement1 = new AnchorElement(MorisonModel1, "AnchorElement1");
AnchorElement1.FairleadNode = 3;
AnchorElement1.WindlassNode = 3;
AnchorElement1.AnchorProperty = AnchorProperty1;
AnchorElement1.XaxisAngle = 300 deg;

AnchorElement2 = new AnchorElement(MorisonModel1, "AnchorElement2");
AnchorElement2.FairleadNode = 4;
AnchorElement2.WindlassNode = 4;
AnchorElement2.AnchorProperty = AnchorProperty1;
AnchorElement2.XaxisAngle = 180 deg;

AnchorElement3 = new AnchorElement(MorisonModel1, "AnchorElement3");
AnchorElement3.FairleadNode = 46;
AnchorElement3.WindlassNode = 46;
AnchorElement3.XaxisAngle = 60 deg;
AnchorElement3.AnchorProperty = AnchorProperty1;

StructureReductions1 = new StructureReductions(Properties, "StructureReductions1");
StructureReduction1 = new StructureReduction(StructureReductions1, "StructureReduction1");
StructureReduction1.Value = new Fraction(0);
Permeabilities1 = new Permeabilities(Properties, "Permeabilities1");
Permeability1 = new Permeability(Permeabilities1, "Permeability1");
Permeability1.Value = new Fraction(1);

Contents1 = new Contents(Properties, "Contents1");
Seawater = new Fluid(Contents1, "Seawater");
Seawater.Density = 1025 kg/m^3;
Seawater.Color = Color.FromArgb(255, 0, 191, 255);
Fixed_ballast = new Fluid(Contents1, "Fixed_ballast");
Fixed_ballast.Density = 2560 kg/m^3;
Fixed_ballast.Color = Color.FromArgb(255, 255, 165, 0);

FillingFractions1 = new FillingFractions(Properties, "FillingFractions1");
Fluid_ballast = new FillingFraction(FillingFractions1, "Fluid_ballast");
Fluid_ballast.Value = new Fraction(0.928417);

CompartmentModel1.FillingFractions.Add(new FillingFractionInterval());
CompartmentModel1.FillingFractions[0].ToFraction = new Fraction(1);
CompartmentModel1.FillingFractions[0].Step = new Fraction(0.1);
CompartmentModel1.ElementModel = Compartment;
CompartmentModel1.UpdateCompartments();
CompartmentModel1.Compartments[6].Group = "P1";
CompartmentModel1.Compartments[7].Group = "P1";
CompartmentModel1.Compartments[8].Group = "P1";
CompartmentModel1.Compartments[9].Group = "P1";
CompartmentModel1.Compartments[24].Group = "P2";
CompartmentModel1.Compartments[27].Group = "P2";
CompartmentModel1.Compartments[30].Group = "P2";
CompartmentModel1.Compartments[32].Group = "P2";
CompartmentModel1.Compartments[28].Group = "P3";
CompartmentModel1.Compartments[29].Group = "P3";
CompartmentModel1.Compartments[31].Group = "P3";
CompartmentModel1.Compartments[40].Group = "P3";


LoadingConditions1 = new LoadingConditions(HydroModel1, "LoadingConditions1");
LoadingCondition1 = new LoadingCondition(LoadingConditions1, "LoadingCondition1");
LoadingCondition1.Location = Location1;
LoadingCondition1.WaterLineZ = 0 m;
LoadingCondition1.TrimAngle = 0 deg;
LoadingCondition1.HeelAngle = 0 deg;

MassModel1 = new MassModel(LoadingCondition1, "MassModel1");
MassModel1.UserSpecifiedMass = 9224290 kg;
MassModel1.UserSpecifiedCenterOfGravityX = 0 m;
MassModel1.UserSpecifiedCenterOfGravityY = 0 m;
MassModel1.UserSpecifiedCenterOfGravityZ = 15.7761 m;
MassModel1.UserSpecifiedRadiusOfGyrationX = 60.42 m;
MassModel1.UserSpecifiedRadiusOfGyrationY = 60.42 m;
MassModel1.UserSpecifiedRadiusOfGyrationZ = 38.377 m;

SecondOrderFreeSurfaceModel1 = new SecondOrderFreeSurfaceModel(LoadingCondition1, "SecondOrderFreeSurfaceModel1");
SecondOrderFreeSurfaceModel1.ElementModel = Free_surface;

CompartmentContents1 = new CompartmentContents(LoadingCondition1, "CompartmentContents1");
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[0].LoadCaseNumber = 2;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[1].LoadCaseNumber = 3;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[2].LoadCaseNumber = 4;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[3].LoadCaseNumber = 5;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[4].LoadCaseNumber = 6;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[5].LoadCaseNumber = 7;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[6].LoadCaseNumber = 8;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[7].LoadCaseNumber = 9;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[8].LoadCaseNumber = 10;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[9].LoadCaseNumber = 11;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[10].LoadCaseNumber = 12;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[11].LoadCaseNumber = 13;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[12].LoadCaseNumber = 14;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[13].LoadCaseNumber = 15;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[14].LoadCaseNumber = 16;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[15].LoadCaseNumber = 17;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[16].LoadCaseNumber = 18;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[17].LoadCaseNumber = 19;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[18].LoadCaseNumber = 20;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[19].LoadCaseNumber = 21;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[20].LoadCaseNumber = 22;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[21].LoadCaseNumber = 23;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[22].LoadCaseNumber = 24;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[23].LoadCaseNumber = 25;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[24].LoadCaseNumber = 26;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[25].LoadCaseNumber = 27;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[26].LoadCaseNumber = 28;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[27].LoadCaseNumber = 29;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[28].LoadCaseNumber = 30;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[29].LoadCaseNumber = 31;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[30].LoadCaseNumber = 32;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[31].LoadCaseNumber = 33;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[32].LoadCaseNumber = 34;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[33].LoadCaseNumber = 35;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[34].LoadCaseNumber = 36;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[35].LoadCaseNumber = 37;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[36].LoadCaseNumber = 38;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[37].LoadCaseNumber = 39;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[38].LoadCaseNumber = 40;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[39].LoadCaseNumber = 41;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[40].LoadCaseNumber = 42;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[41].LoadCaseNumber = 43;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[42].LoadCaseNumber = 44;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[43].LoadCaseNumber = 45;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[44].LoadCaseNumber = 46;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[45].LoadCaseNumber = 47;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[46].LoadCaseNumber = 48;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[47].LoadCaseNumber = 49;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[48].LoadCaseNumber = 50;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[49].LoadCaseNumber = 51;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[50].LoadCaseNumber = 52;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[51].LoadCaseNumber = 53;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[52].LoadCaseNumber = 54;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[53].LoadCaseNumber = 55;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[54].LoadCaseNumber = 56;
CompartmentContents1.Contents.Add(new CompartmentContent());
CompartmentContents1.Contents[55].LoadCaseNumber = 57;
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[0].Name = "LC2";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[1].Name = "LC3";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[2].Name = "LC4";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[3].Name = "LC5";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[4].Name = "LC6";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[5].Name = "LC7";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[6].Name = "P1";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[7].Name = "LC12";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[8].Name = "LC13";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[9].Name = "LC14";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[10].Name = "LC15";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[11].Name = "LC16";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[12].Name = "LC17";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[13].Name = "LC18";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[14].Name = "LC19";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[15].Name = "LC20";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[16].Name = "LC21";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[17].Name = "LC22";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[18].Name = "LC23";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[19].Name = "LC24";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[20].Name = "LC25";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[21].Name = "P2";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[22].Name = "LC27";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[23].Name = "LC28";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[24].Name = "P3";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[25].Name = "LC35";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[26].Name = "LC36";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[27].Name = "LC37";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[28].Name = "LC38";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[29].Name = "LC39";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[30].Name = "LC40";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[31].Name = "LC41";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[32].Name = "LC43";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[33].Name = "LC44";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[34].Name = "LC45";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[35].Name = "LC46";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[36].Name = "LC47";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[37].Name = "LC48";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[38].Name = "LC49";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[39].Name = "LC50";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[40].Name = "LC51";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[41].Name = "LC52";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[42].Name = "LC53";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[43].Name = "LC54";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[44].Name = "LC55";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[45].Name = "LC56";
CompartmentContents1.GroupSettings.Add(new CompartmentGroup());
CompartmentContents1.GroupSettings[46].Name = "LC57";

CompartmentContents1.Contents[6].IntactFluid = Seawater;
CompartmentContents1.Contents[7].IntactFluid = Seawater;
CompartmentContents1.Contents[8].IntactFluid = Seawater;
CompartmentContents1.Contents[9].IntactFluid = Seawater;
CompartmentContents1.Contents[24].IntactFluid = Seawater;
CompartmentContents1.Contents[27].IntactFluid = Seawater;
CompartmentContents1.Contents[28].IntactFluid = Seawater;
CompartmentContents1.Contents[28].IntactFluid = Seawater;
CompartmentContents1.Contents[29].IntactFluid = Seawater;
CompartmentContents1.Contents[30].IntactFluid = Seawater;
CompartmentContents1.Contents[31].IntactFluid = Seawater;
CompartmentContents1.Contents[32].IntactFluid = Seawater;
CompartmentContents1.Contents[40].IntactFluid = Seawater;

CompartmentContents1.Contents[9].FillingFraction = Fluid_ballast;
CompartmentContents1.Contents[8].FillingFraction = Fluid_ballast;
CompartmentContents1.Contents[7].FillingFraction = Fluid_ballast;
CompartmentContents1.Contents[6].FillingFraction = Fluid_ballast;
CompartmentContents1.Contents[32].FillingFraction = Fluid_ballast;
CompartmentContents1.Contents[30].FillingFraction = Fluid_ballast;
CompartmentContents1.Contents[24].FillingFraction = Fluid_ballast;
CompartmentContents1.Contents[27].FillingFraction = Fluid_ballast;
CompartmentContents1.Contents[31].FillingFraction = Fluid_ballast;
CompartmentContents1.Contents[29].FillingFraction = Fluid_ballast;
CompartmentContents1.Contents[28].FillingFraction = Fluid_ballast;
CompartmentContents1.Contents[40].FillingFraction = Fluid_ballast;

CompartmentContents1.AdjustmentMethod = CompartmentContentAdjustmentMethod.ByGroup;
CompartmentContents1.GroupSettings[6].IsAdjustable = true;
CompartmentContents1.GroupSettings[21].IsAdjustable = true;
CompartmentContents1.GroupSettings[24].IsAdjustable = true;

AdditionalMatrices1 = new AdditionalMatrices(LoadingCondition1, "AdditionalMatrices1");
CriticalDampingMatrix1 = new CriticalDampingMatrix(AdditionalMatrices1, "CriticalDampingMatrix1");
CriticalDampingMatrix1.Heave = 0.05;
CriticalDampingMatrix1.Roll = 0.05;
CriticalDampingMatrix1.Pitch = 0.05;

FixedLids1 = new FixedLids(LoadingCondition1, "FixedLids1");
FixedLid1 = new FixedLid(FixedLids1, "FixedLid1");
FixedLid1.ElementModel = Internal_lid;


WadamAnalysis1.DataPreparation = true;
WadamAnalysis1.ExecuteAnalysis = true;
WadamAnalysis1.ToleranceWaterline = new Fraction(0.05);
WadamAnalysis1.ToleranceCOG = new Fraction(0.05);
WadamAnalysis1.CharacteristicLength = 100 m;
WadamAnalysis1.AnnulusSize = 500 m;
WadamAnalysis1.UseFreeSurfaceIntegral = true;
WadamAnalysis1.TranslationalConvergenceCriteria = new Fraction(0.001);
WadamAnalysis1.RotationalConvergenceCriteria = new Fraction(0.001);
WadamAnalysis1.MaxLinearizationIterations = 20;
WadamAnalysis1.UseStochasticLinearization = true;
WadamAnalysis1.MaxMatrixSize = 50000;
WadamAnalysis1.MaximumRollAngleItems.Add(new MaximumRollAngleItem());
WadamAnalysis1.MaximumRollAngleItems.Add(new MaximumRollAngleItem());
WadamAnalysis1.MaximumRollAngleItems.Add(new MaximumRollAngleItem());
WadamAnalysis1.MaximumRollAngleItems.Add(new MaximumRollAngleItem());
WadamAnalysis1.MaximumRollAngleItems.Add(new MaximumRollAngleItem());
WadamAnalysis1.MaximumRollAngleItems.Add(new MaximumRollAngleItem());
WadamAnalysis1.MaximumRollAngleItems.Add(new MaximumRollAngleItem());
WadamAnalysis1.MaximumRollAngleItems.Add(new MaximumRollAngleItem());
WadamAnalysis1.MaximumRollAngleItems.Add(new MaximumRollAngleItem());
WadamAnalysis1.MaximumRollAngleItems[0].MaxRollAngle = 0.1 deg;
WadamAnalysis1.MaximumRollAngleItems[1].Heading = 45 deg;
WadamAnalysis1.MaximumRollAngleItems[1].MaxRollAngle = 2.5 deg;
WadamAnalysis1.MaximumRollAngleItems[2].Heading = 90 deg;
WadamAnalysis1.MaximumRollAngleItems[2].MaxRollAngle = 4 deg;
WadamAnalysis1.MaximumRollAngleItems[3].Heading = 135 deg;
WadamAnalysis1.MaximumRollAngleItems[3].MaxRollAngle = 2.5 deg;
WadamAnalysis1.MaximumRollAngleItems[4].Heading = 180 deg;
WadamAnalysis1.MaximumRollAngleItems[4].MaxRollAngle = 0.1 deg;
WadamAnalysis1.MaximumRollAngleItems[5].Heading = 225 deg;
WadamAnalysis1.MaximumRollAngleItems[5].MaxRollAngle = 2.5 deg;
WadamAnalysis1.MaximumRollAngleItems[6].Heading = 270 deg;
WadamAnalysis1.MaximumRollAngleItems[6].MaxRollAngle = 4 deg;
WadamAnalysis1.MaximumRollAngleItems[7].Heading = 315 deg;
WadamAnalysis1.MaximumRollAngleItems[7].MaxRollAngle = 2.5 deg;
WadamAnalysis1.MaximumRollAngleItems[8].Heading = 360 deg;
WadamAnalysis1.MaximumRollAngleItems[8].MaxRollAngle = 0.1 deg;
WadamAnalysis1.CalculateEigenvalues = true;
WadamAnalysis1.PrintType = PrintType.NormalPrint;
WadamAnalysis1.PanelPlateOutOfPlaneTolerance = new Fraction(0.8);
WadamAnalysis1.PanelToPlateAngularDifference = 20 deg;
WadamAnalysis1.LoadTransferPressureReductionZoneExtension = 1 m;
WadamAnalysis1.LoadTransferIncludeStaticLoad = true;
WadamAnalysis1.LoadTransferIncludeStaticGravity = true;
WadamAnalysis1.LoadTransferIncludeInertia = true;
WadamAnalysis1.LoadTransferIncludeFluctuatingGravity = true;
WadamAnalysis1.LoadTransferIncludeFluctuatingPressure = true;
WadamAnalysis1.LoadTransferIncludeMooringLoad = true;
WadamAnalysis1.CalculateDriftForces = true;
WadamAnalysis1.FarFieldIntegration = true;
WadamAnalysis1.UseRollGZCurve = true;
WadamAnalysis1.SaveRestartFileName = "WADAM";
WadamAnalysis1.HydroModel = HydroModel1;
WadamAnalysis1.LoadingCondition = LoadingCondition1;
WadamAnalysis1.UseStochasticLinearization = false;
WadamAnalysis1.UseRollGZCurve = false;
WadamAnalysis1.UseMorisonModel = true;
WadamAnalysis1.RemoveIrregularFrequencies = true;
WadamAnalysis1.EnvironmentCondition = FrequencyDomainCondition1;
WadamAnalysis1.SaveWamitFiles = true;

WadamAnalysis1.UseMorisonModel = false;
WadamAnalysis1.CalculateDriftForces = false;
WadamAnalysis1.DifferenceFrequencies = false;
WadamAnalysis1.IncludeLimitingFrequencies = true;
WadamAnalysis1.IncludeForwardSpeed = false;